import { AlgorithmCode } from '@/types/algorithm';

export const hanoiCode: Record<string, AlgorithmCode> = {
  javascript: {
    language: 'javascript',
    lines: [
      'function towerOfHanoi(n, source, auxiliary, target) {',
      '  // Base case: only one disk',
      '  if (n === 1) {',
      '    move(source, target);',
      '    return;',
      '  }',
      '  ',
      '  // Move n-1 disks from source to auxiliary',
      '  towerOfHanoi(n - 1, source, target, auxiliary);',
      '  ',
      '  // Move the largest disk from source to target',
      '  move(source, target);',
      '  ',
      '  // Move n-1 disks from auxiliary to target',
      '  towerOfHanoi(n - 1, auxiliary, source, target);',
      '}',
      '',
      '// Helper function to move a disk',
      'function move(from, to) {',
      '  const disk = from.pop();',
      '  to.push(disk);',
      '}',
    ],
  },
  python: {
    language: 'python',
    lines: [
      'def tower_of_hanoi(n, source, auxiliary, target):',
      '    # Base case: only one disk',
      '    if n == 1:',
      '        move(source, target)',
      '        return',
      '    ',
      '    # Move n-1 disks from source to auxiliary',
      '    tower_of_hanoi(n - 1, source, target, auxiliary)',
      '    ',
      '    # Move the largest disk from source to target',
      '    move(source, target)',
      '    ',
      '    # Move n-1 disks from auxiliary to target',
      '    tower_of_hanoi(n - 1, auxiliary, source, target)',
      '',
      '# Helper function to move a disk',
      'def move(from_rod, to_rod):',
      '    disk = from_rod.pop()',
      '    to_rod.append(disk)',
    ],
  },
  pseudocode: {
    language: 'pseudocode',
    lines: [
      'TOWER_OF_HANOI(n, source, auxiliary, target):',
      '    // Base case: only one disk to move',
      '    IF n = 1 THEN',
      '        MOVE disk from source TO target',
      '        RETURN',
      '    END IF',
      '    ',
      '    // Recursive case:',
      '    // Step 1: Move n-1 disks from source to auxiliary',
      '    TOWER_OF_HANOI(n-1, source, target, auxiliary)',
      '    ',
      '    // Step 2: Move largest disk from source to target',
      '    MOVE disk from source TO target',
      '    ',
      '    // Step 3: Move n-1 disks from auxiliary to target',
      '    TOWER_OF_HANOI(n-1, auxiliary, source, target)',
    ],
  },
};
